### ISSUE TITLE
[Feature] Add Reference-Style Links

### ISSUE THREAD

**Issue by electblake** [mii-key/obsidian-links#20]
## Context / Problem
- Seems like this plugin only works with inline style markdown links, what about reference style links?

[Reference style links](https://www.markdownguide.org/basic-syntax/#reference-style-links) are quite handy when using source viewing, and doubly-so when working with tables which contain links.

- Inline links in tables cause "clean" table-markdown formatting to expand to fit urls, so far that I can barely manage on table mobile or other small form-factors clients
  - This experience is especially difficult when using [advanced-tables plugin](https://github.com/tgrosinger/advanced-tables-obsidian) with automatic table markdown formatting
- Inline links in normal paragraphs are ok, but for my more ever-green notes I reference frequently I like to convert them to reference-style to save screen space and make the reading experience easier in source, as well as less on-screen changes when I swap to preview mode

**In generally, my goal is to save screen space, make tables w/links more manageable, and less delta between preview and source views by using reference-style markdown links**

## Proposal
> Add reference-style link support to this plugin

- I'd propose something simple to start, a stand-alone set of commands similar to others to convert to and from inline to reference style links
- reference style links needs a reference to use - I propose something simple to start, something like one of:
  - auto-increment number
  - url hash
  - shortcode id like https://github.com/ai/nanoid/
  - personally I prefer the shortest possible, saving screen space is my goal here

### Bonus / Future Scope

- De-duplication of referenced links in note (Note: url hash references should do this nearly for free)
- Add option to other commands to use reference-style links holistically with plugin

**Comment by mii-key** [comment]
Thank you for using the plugin and for your valuable suggestion.

I appreciate your input and will definitely consider it. 

However, there are a few issues, that in my opinion, make this feature less useful for the majority of users:
- lack of reference-style links support in Obsidian with no ETA. (<https://forum.obsidian.md/t/support-reference-links-in-edit-mode-live-preview-reference-style/32286/8>)
- support of only URLs (<https://www.markdownguide.org/basic-syntax/#reference-style-links>) most probably defeats the whole value of using this type of link for most of the users in Obsidian, since links on internal notes are usually far more frequent than external links.

That said, I think this could be a wonderful feature in the future when the aforementioned problems can be solved.
